# ado-pipeline-simple-api.yml
# Version: 0.0.1
# Created by: Alvaro Garcia

name: "$(Date:yyyy-MM-dd)_simple-api-build-and-test-${{ parameters.environment }}-$(Rev:.r)"

trigger: none

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - qa
      - prod

stages:
  - stage: Deploy
    displayName: 'Deploying and Testing simple-api ${{ parameters.environment }}'
    jobs:
    - job: BuildAndTest
      displayName: 'Building, Deploying and Testing simple-api'
      workspace:
        clean: all

      pool:
        vmImage: ubuntu-latest # Remember to mention in README.md which software is included here to keep in mind. (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)

      steps:

      - task: DownloadSecureFile@1
        name: GoogleCredentials
        displayName: 'Download GOOGLE_CREDENTIALS'
        inputs:
          secureFile: 'gcp-creds-${{ parameters.environment }}.json'

      - script: |
          mkdir '$(Build.ArtifactStagingDirectory)/ci-cd'
          mv $(GoogleCredentials.secureFilePath) '$(Build.ArtifactStagingDirectory)/ci-cd/google-sa.json'
        displayName: 'Copying google-sa.json for env: ${{ parameters.environment }}'

      - task: CopyFiles@2
        inputs:
          SourceFolder: 'ci-cd'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/ci-cd'
        displayName: 'Copy ci-cd folder'

      - script: |
          cd $(Build.ArtifactStagingDirectory)/ci-cd
          ls -lra
          docker-compose -f docker-compose-${{ parameters.environment }}.yml up -d
          docker exec ci-cd-simple-api-${{ parameters.environment }} yarn run test
        displayName: 'Build and Test Dev'
