# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
 - develop
 - qa
 - production

pool:
  vmImage: ubuntu-latest # Remember to mention in README.md which software is included here to keep in mind. (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '>=18.10'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'simple-api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/simple-api'
  displayName: 'Copy simple-api folder'

- script: |
    cd $(Build.ArtifactStagingDirectory)/simple-api
    npm install
    yarn install    
  displayName: 'Install npm and yarn'

- script: |
    cd $(Build.ArtifactStagingDirectory)/simple-api
    yarn run test
  displayName: 'Run Unit Tests'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: simple-api
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'