# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# https://www.youtube.com/watch?v=z_4sMQKE_zw
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker version  
  displayName: 'Show docker version'

- task: NodeTool@0
  inputs:
    versionSpec: '>=18.10'
  displayName: 'Install Node.js'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'simple-api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/simple-api'
  displayName: 'Copy simple-api folder'

- script: |
    cd $(Build.ArtifactStagingDirectory)/simple-api
    npm install
    yarn install    
  displayName: 'Install npm and yarn'

- script: |
    cd $(Build.ArtifactStagingDirectory)/simple-api
    yarn run test
  displayName: 'Run Unit Tests'