version: '3'
services:
  simple-api-dev:
    container_name: nameci-cd-simple-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_CREDENTIALS}
    command: ["yarn", "run", "start"]