version: '3'
services:
  simple-api-dev:
    container_name: ci-cd-simple-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=watch
    command: ["yarn", "run", "start:watch"]
