version: '3'
services:
  simple-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_CREDENTIALS}
    command: ["yarn", "run", "start:prod"]